name = "yarbo-recruitment"
compatibility_date = "2024-07-29"
compatibility_flags = ["nodejs_compat"]
pages_build_output_dir = ".vercel/output/static"

[env.production.vars]
NEXT_PUBLIC_SUPABASE_URL = "https://eipqxgdqittupttmpiud.supabase.co"
***REMOVED*** = "***REMOVED***"
***REMOVED*** = "***REMOVED***"
NEXT_PUBLIC_APP_URL = "https://yarbo-recruitment.pages.dev"
