name = "yarbo-recruitment"
compatibility_date = "2024-07-29"
compatibility_flags = ["nodejs_compat"]
pages_build_output_dir = "yarbo-app/.vercel/output/static"

[env.production]
compatibility_flags = ["nodejs_compat"]

[env.preview]
compatibility_flags = ["nodejs_compat"]

# Pages Functions 环境变量
# 注意：敏感密钥应该在 Cloudflare Pages 控制台中设置，而不是写在此文件中
[vars]
NEXT_PUBLIC_SUPABASE_URL = "https://eipqxgdqittupttmpiud.supabase.co"
NEXT_PUBLIC_APP_URL = "https://yarbo-recruitment.pages.dev"

[env.production.vars]
NEXT_PUBLIC_SUPABASE_URL = "https://eipqxgdqittupttmpiud.supabase.co"
NEXT_PUBLIC_APP_URL = "https://yarbo-recruitment.pages.dev"

# 敏感密钥需要在 Cloudflare Pages 控制台中设置：
# NEXT_PUBLIC_SUPABASE_ANON_KEY
# SUPABASE_SERVICE_ROLE_KEY
