name = "yarbo-api"
main = "src/index.js"
compatibility_date = "2024-07-29"

[env.production.vars]
ENVIRONMENT = "production"

[env.development.vars]
ENVIRONMENT = "development"

# 环境变量将通过 wrangler secret 设置
# NEXT_PUBLIC_SUPABASE_URL
# SUPABASE_SERVICE_ROLE_KEY
